### ISSUE TITLE
常にTrueのif文がある。

### ISSUE THREAD

**Issue by hawk-tomy** [DiscordBotPortalJP/dispander#13]
現在のコードのmodule.pyの25行目
```py
    for m in messages:
        if message.content:
            await message.channel.send(embed=compose_embed(m))
```
のif文の条件はforのブロックの中が実行されたときには常にTrueになってしまい、`m.content`が空の文字列の場合、空の埋め込みが送信されてしまっています。
多分`message.content`ではなく`m.content`のミスだと思うので、修正していただけるとありがたいです。

**Comment by Huyu2239** [comment]
https://github.com/DiscordBotPortalJP/dispander/commit/a9f2fb4ab516c1b7df30a8350c1b97f5aaaf8c66
https://github.com/DiscordBotPortalJP/dispander/commit/8c2fc65361c33d6e7422aadc3ba334c52232a6d2

fixed
