### ISSUE TITLE
展開に返信を使うか

### ISSUE THREAD

**Issue by sevenc-nanashi** [DiscordBotPortalJP/dispander#16]
![image](https://user-images.githubusercontent.com/59691627/116543612-081fff00-a929-11eb-9d5b-df79af01724e.png)
上が現在、下が返信を使った場合。
意見を聞きたいです。

**Comment by Huyu2239** [comment]
それだと、一つのメッセージに複数URLが入ってた場合、毎回返信の表示が入るので見づらいかと
返信を一回目だけになるように書き換えるにしても、そこまでするメリットがあるかどうかになりますね

個人的には上がいいと思います

**Comment by yutarou12** [comment]
同感

**Comment by 1ntegrale9** [comment]
超遅レスですが、チャンネルを超えた展開で返信が使えないので、場所によって表示が異なるのがあまり良くないため返信はナシで良いかなと思います
