### ISSUE TITLE
複数桁IDに対応すると<>付与時に動作が止まる

### ISSUE THREAD

**Issue by la-png** [DiscordBotPortalJP/dispander#38]
ID増加や、初期の発言を考慮してIDの対応桁数を増やすと、URLの直後に>がある場合に動作停止する問題があります。

これはメッセージリンクを判定する正規表現の問題で、単純に桁数を増やして
`(?!<)https://(ptb.|canary.)?discord(app)?.com/channels/(?P<guild>[0-9]{17,20})/(?P<channel>[0-9]{17,20})/(?P<message>[0-9]{17,20})(?!>)`
としてしまうと、…/12345678912345678>のような18桁IDが来ると、より短い17桁IDの…/1234567891234567としてマッチしてしまい、存在しないメッセージを取得しようとしてfetch_message_from_id()で404が出るうことが原因です。

なお、動作が停止することで擬似的に引用されなくはなりますが、<>で囲ったURLと囲っていないURLを同時に発言すると囲っていないURLも動作しなくなりますし、余計なAPIリクエストが発生するため、好ましい挙動とは言えません。

**Comment by la-png** [comment]
末尾を`(?![0-9>])`にすれば良い、との案を名無しさんが提示してくれたので転記

**Comment by 1ntegrale9** [comment]
#36 #37 にて対応済みのため close
